### ISSUE TITLE
Error while using uploaded config.yaml

### ISSUE THREAD

**Issue by rrbanda** [promptfoo/promptfoo#1273]
Got the following error while running an eval 

```
Writing environment variables to .env file...
Loaded environment variables:
entrypoint.sh: line 3: can't create /app/src/web/nextui/.env: Permission denied
cat: can't open '/app/src/web/nextui/.env': No such file or directory
Starting server...
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
Listening on port 3000 url: http://0.0.0.0:3000
[1539e61f-74bd-447e-8811-576303d7e300] 1/4
[1539e61f-74bd-447e-8811-576303d7e300] 2/4
[1539e61f-74bd-447e-8811-576303d7e300] 3/4
[1539e61f-74bd-447e-8811-576303d7e300] 4/4
[31mError running database migrations: EACCES: permission denied, mkdir '/.promptfoo'[39m
Error: EACCES: permission denied, mkdir '/.promptfoo'
[90m    at Object.mkdirSync (node:fs:1372:26)[39m
    at getConfigDirectoryPath [90m(/app/src/web/nextui/[39m.next/server/chunks/6423.js:1279:41[90m)[39m
    at getDbPath [90m(/app/src/web/nextui/[39m.next/server/chunks/6423.js:60:131[90m)[39m
    at getDb [90m(/app/src/web/nextui/[39m.next/server/chunks/6423.js:67:84[90m)[39m
    at writeResultsToDatabase [90m(/app/src/web/nextui/[39m.next/server/chunks/6423.js:1669:42[90m)[39m
    at Object.index_evaluate [as evaluate] [90m(/app/src/web/nextui/[39m.next/server/app/api/eval/job/route.js:9603:63[90m)[39m
[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m {
  errno: [33m-13[39m,
  code: [32m'EACCES'[39m,
  syscall: [32m'mkdir'[39m,
  path: [32m'/.promptfoo'[39m
}
```

cc @mldangelo @IanCal

**Comment by rrbanda** [comment]
https://github.com/user-attachments/assets/710c8a3b-6c38-4743-91a9-9c1125a5cedb

The evaluation keeps rotating at 100 % on the UI

**Comment by rrbanda** [comment]
@IanCal @mldangelo Can you please share an example` config.yaml` that i could use to test with running using docker and kubernetes using upload button  ?

**Comment by mldangelo** [comment]
Hey @rrbanda, first off, I want to sincerely apologize for the delay in getting back to you. I really appreciate your involvement and patience. The issue you encountered should now be resolved. If you try again with the latest version, everything should work as expected. Please don't hesitate to reach out if you run into any more issues, and thank you again for helping us improve Promptfoo!

**Comment by vgupta1992** [comment]
Hello @mldangelo ,

I am using promptfoo v-0.101.2 but still facing this issue on code deployment.

![image (2)](https://github.com/user-attachments/assets/f7eae15e-9c35-4b93-bacc-aac23637a8f3)

Thanks.
