### ISSUE TITLE
Importing Promptfoo prevents Node from exiting naturally

### ISSUE THREAD

**Issue by justindilen** [promptfoo/promptfoo#5893]
**Describe the bug**
When importing the npm package, it seems to create a process that prevents node from exiting without even invoking anything.

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

1. Create a node project (with package.json "type": "module") and install latest promptfoo
2. Import promptfoo in a JS file like so:
 ```
import promptfoo from 'promptfoo';
```
3. Run the file using node: `node ./test.js`
4. Notice the node process never exits naturally

**Expected behavior**
Node should quickly exit instead of hanging. 
In general, even if promptfoo eval is run, it should cleanup any resources / timeouts and naturally exit.

**System information:**

- Promptfoo version: 0.118.14
- Node version: 22.13.1
- Windows 10, powershell terminal

**Additional context**
Earlier versions of promptfoo did not seem to have this issue. Testing shows that release 0.118.7 has this issue, but 0.118.6 does not.

**Comment by mldangelo** [comment]
Hi @justindilen,

Sorry for the bug and for not closing this sooner - this was fixed in **PR #5698** on September 23, 2025 (before you reported it), released in version 0.118.8.

The PostHog client was keeping connections open and preventing Node from exiting naturally. This has been resolved - the process now exits cleanly after commands complete.

Please pull the latest version and the issue should be gone. If you experience any other issues, feel free to comment or re-open.

See the [Command Line documentation](https://www.promptfoo.dev/docs/usage/command-line) for more info.

Thanks for the report!

**Comment by justindilen** [comment]
> Hi [@justindilen](https://github.com/justindilen),
> 
> Sorry for the bug and for not closing this sooner - this was fixed in **PR [#5698](https://github.com/promptfoo/promptfoo/pull/5698)** on September 23, 2025 (before you reported it), released in version 0.118.8.
> 
> The PostHog client was keeping connections open and preventing Node from exiting naturally. This has been resolved - the process now exits cleanly after commands complete.
> 
> Please pull the latest version and the issue should be gone. If you experience any other issues, feel free to comment or re-open.
> 
> See the [Command Line documentation](https://www.promptfoo.dev/docs/usage/command-line) for more info.
> 
> Thanks for the report!

@mldangelo  Appreciate the response. 

Unfortunately, in the original post I was testing using 0.118.14 and was having this issue, so I don't think it was fixed in 0.118.8.

To further confirm, I pulled the latest (0.118.17 as of writing), and this is still an issue.
I also tried your suggested version (0.118.8), and I am also seeing the issue there. 
Seems like only using version  0.118.6 and earlier fixes it.

It looks like I do not have permissions to re-open, but it would be nice if this could still be addressed. We use the promptfoo tool in our CI/CD pipelines, and this issue prevents us from using the latest version as it never exits and times out our pipelines.
