### ISSUE TITLE
Migrations path incorrect in self host docker build

### ISSUE THREAD

**Issue by drien** [promptfoo/promptfoo#861]
When I run the provided Dockerfile as described via the docs, I get the following migrations related error:

```
Running migrations from /app/src/web/nextui/.next/server/drizzle...
Error running database migrations: Can't find meta/_journal.json file
SqliteError: no such table: evals
    at Database.prepare (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at BetterSQLiteSession.prepareQuery (/app/src/web/nextui/.next/server/chunks/7877.js:106655:34)
    at BetterSQLiteSession.prepareOneTimeQuery (/app/src/web/nextui/.next/server/chunks/7877.js:106587:21)
    at QueryPromise._prepare (/app/src/web/nextui/.next/server/chunks/7877.js:105976:85)
    at SQLiteInsertBase.run (/app/src/web/nextui/.next/server/chunks/7877.js:105872:25)
    at writeResultsToDatabase (/app/src/web/nextui/.next/server/chunks/7398.js:6159:30)
    at Object.index_evaluate [as evaluate] (/app/src/web/nextui/.next/server/app/api/eval/job/route.js:3537:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'SQLITE_ERROR'
}
```
Some inspection of the code an image contents image contents shows the migrations folder path in migrations.ts seems to be the culprit: https://github.com/promptfoo/promptfoo/blob/f7c420e7179792676ad870dba4b8bdf5b2cb3667/src/migrate.ts#L13

It looks like this path is set to the non-built folder structure, but changes to the folder structure happen during the docker build in a way that breaks the reference.

Everything works as expected if I hardcode the drizzle path like this:

```javascript
    const migrationsFolder = '/app/drizzle/'; // path.join(__dirname, '..', 'drizzle');
```
I'm not well versed enough in nextjs/the build process generally to offer a fix right off the bat but happy to contribute if I happen to figure it out.

**Comment by typpo** [comment]
Hey @drien, thanks for digging into this.  Just pushed a change that should resolve this I think.

**Comment by drien** [comment]
That seemed to fix it! Thanks for the quick reply. I ran into another issue when testing the fix on the current main brain that I'll pop a PR for.

**Comment by jay0129** [comment]
@typpo I still get the same problem for the latest commit today.

The first attempt to create the db file fails.
`Running migrations from /app/src/web/nextui/.next/server/drizzle...`
Because, in the path there is no directory `drizzle`.
Reference code:
https://github.com/promptfoo/promptfoo/blob/f302eb232d9a4a567016a84d6129ad76b6941bf7/src/migrate.ts#L15

Hard coding this value solves the problem:
`    const migrationsFolder = '/app/drizzle/'; // path.join(__dirname, '..', 'drizzle');`

Should we change the following code:
https://github.com/promptfoo/promptfoo/blob/f302eb232d9a4a567016a84d6129ad76b6941bf7/Dockerfile#L48

to 
`COPY --from=builder /app/drizzle ./src/web/nextui/.next/server/drizzle`

?

**Comment by typpo** [comment]
Thanks for catching @jay0129, that resolves the share issue.  Fixed in 6a1eef4e4b006b32de9ce6e5e2d7c0bd3b9fa95a
